<?php include 'head.php'; ?>
<?php include 'header.php'; ?>
<?php include 'carousel.php'; ?>
<?php include 'about.php'; ?>
<?php include 'clients.php'; ?>
<?php include 'services.php'; ?>
<?php include 'courses.php'; ?>
<?php include 'testimonials.php'; ?>
<?php include 'team.php'; ?>
<?php include 'contact.php'; ?>
<?php include 'footer.php'; ?>
